# ======================================================================
# ==                  CONFIGURACIÓN PRINCIPAL DEL SITIO               ==
# ======================================================================
site_name: IPV WEB
site_author: Iker Pazos
site_description: Portfolio profesional y blog de Iker Pazos, especializado en Inteligencia Artifial y Big Data.
repo_url: https://github.com/iker-pazos/iker-pazos.github.io

# ======================================================================
# ==                      ESTRUCTURA DE NAVEGACIÓN                    ==
# ======================================================================
nav:
  - 'INICIO': 'home.md'
  - 'SOBRE MÍ': 'home.md#sobre-mi'
  - 'PROYECTOS': 'home.md#proyectos'
  - 'CONTACTO': 'home.md#contacto'

# ======================================================================
# ==                      CONFIGURACIÓN DEL TEMA                      ==
# ======================================================================
theme:
  name: material
  language: es
  logo: assets/PBLANCA.png
  favicon: assets/PBLANCA.png
  icon:
    repo: fontawesome/brands/github
    custom_dir: .icons/simple
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: slate
      primary: black
      accent: indigo
  features:
    - header.autohide
    - navigation.tracking
    - navigation.instant
    - navigation.sections
    - navigation.instant.animation
    - navigation.top
    # - toc.integrate # Correctamente desactivado
    - announce.dismiss

# ======================================================================
# ==                   PERSONALIZACIONES AVANZADAS                    ==
# ======================================================================
extra_css:
  - https://unpkg.com/aos@next/dist/aos.css 
  - stylesheets/extra.css

extra_javascript:
  - javascript/tsparticles.bundle.min.js
  - javascript/particles-config.js
  - https://unpkg.com/aos@next/dist/aos.js 
  - javascript/custom.js      
# ======================================================================
# ==                  EXTENSIONES DE MARKDOWN                         ==
# ======================================================================
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg