# ======================================================================
# ==                  CONFIGURACIÓN PRINCIPAL DEL SITIO               ==
# ======================================================================
site_name: IPV WEB
site_author: Iker Pazos
site_description: Portfolio profesional y blog de Iker Pazos, especializado en desarrollo web.
repo_url: https://github.com/iker-pazos/iker-pazos.github.io

# ======================================================================
# ==                      ESTRUCTURA DE NAVEGACIÓN                    ==
# ======================================================================
nav:
  - 'INICIO': 'home.md'
  - 'SOBRE MÍ': 'sobre-mi.md'
  - 'PROYECTOS': 'proyectos.md'
  - 'CONTACTO': 'contacto.md'

# ======================================================================
# ==                      CONFIGURACIÓN DEL TEMA                      ==
# ======================================================================
theme:
  name: material
  language: es
  logo: assets/PBLANCA.png
  favicon: assets/favicon.png
  #custom_dir: overrides # Comentado, ya no es necesario
  
  # --- PAQUETES DE ICONOS A CARGAR ---
  icon:
    repo: fontawesome/brands/github
    # Carga la colección de 'Simple Icons' para LinkedIn, etc.
    custom_dir: .icons/simple

  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: slate
      primary: black
      accent: indigo
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
    #- navigation.instant.progress
    - navigation.instant.animation
    - navigation.top
    - toc.integrate
    - announce.dismiss

# ======================================================================
# ==                   PERSONALIZACIONES AVANZADAS                    ==
# ======================================================================
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/tsparticles.bundle.min.js
  - javascript/particles-config.js

# ======================================================================
# ==                  EXTENSIONES DE MARKDOWN                         ==
# ======================================================================
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  # --- EXTENSIONES PARA PROCESAR ICONOS ---
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg